// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_crystal_guard = "CgkIw_e32rQYEAIQAQ"; // <GPGSID>
        public const string achievement_completionist = "CgkIw_e32rQYEAIQCQ"; // <GPGSID>
        public const string achievement_builder = "CgkIw_e32rQYEAIQBA"; // <GPGSID>
        public const string achievement_crystal_protector = "CgkIw_e32rQYEAIQAg"; // <GPGSID>
        public const string achievement_artisan = "CgkIw_e32rQYEAIQBQ"; // <GPGSID>
        public const string leaderboard_awesome_leaderboard = "CgkIw_e32rQYEAIQBg"; // <GPGSID>
        public const string achievement_craftsman = "CgkIw_e32rQYEAIQBw"; // <GPGSID>
        public const string achievement_tutorial_master = "CgkIw_e32rQYEAIQCA"; // <GPGSID>
        public const string achievement_crystal_guardian = "CgkIw_e32rQYEAIQAw"; // <GPGSID>
        public const string achievement_extreme_completionist = "CgkIw_e32rQYEAIQCg"; // <GPGSID>

}

